### ISSUE TITLE
getComments display errors

### ISSUE THREAD

**Issue by fredleger** [yukicountry/realworld-nextjs-rsc#1]
Using Flask implementation fetching comments from articles throws an error :

![image](https://github.com/user-attachments/assets/681b7ba0-b572-40f7-9c51-f7bd8287d446)

From Front
```
GET / 200 in 112ms
 ⨯ node_modules/zod/lib/index.mjs (587:1) @ get error [as error]
 ⨯ ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "number",
    "path": [
      "id"
    ],
    "message": "Expected string, received number"
  }
]
    at eval (./src/modules/features/article/fetch/fetchComments.ts:21:111)
    at Array.map (<anonymous>)
    at fetchComments (./src/modules/features/article/fetch/fetchComments.ts:21:39)
    at async CommentList (./src/app/article/[slug]/_components/commentList/commentList.tsx:20:22)
digest: "3841490502"
  585 |                 if (this._error)
  586 |                     return this._error;
> 587 |                 const error = new ZodError(ctx.common.issues);
      | ^
  588 |                 this._error = error;
  589 |                 return this._error;
  590 |             },
 GET /article/plop-RSyx86j1ekY 200 in 149ms
```

From API
```JSON
{"path": "/api/v1/articles/plop-RSyx86j1ekY/comments", "method": "GET", "query": "", "status": 200, "duration": 0.054, "event": "HTTP request processed", "request_id": "4e7f61487ceb4b80ab7e341a5d1330fe", "level": "info", "timestamp": "2024-11-14T21:45:43.248238Z", "lineno": 45, "filename": "middlewares.py", "func_name": "logging_middleware"}
```

**Comment by yukicountry** [comment]
Thank you for the comment! I'll check it.
